version: '3.8'

services:

  #php
  app:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile
    container_name: ppww-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../wordpress/:/var/www

  #redis
  redis:
    image: redis:7-alpine
    container_name: ppwy-redis

  #web server
  nginx:
    image: nginx:1.25-alpine
    container_name: ppwy-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../wordpress/:/var/www
      - ../.docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ../.docker/nginx/conf.d:/etc/nginx/conf.d

  #mysql
  db:
    image: mysql:5.7.8
    container_name: ppwy-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ../.data/mysql/:/var/lib/mysql/
